
# Auth configuration
[auth]
site_url = "https://your-production-domain.vercel.app"
additional_redirect_urls = ["https://your-production-domain.vercel.app/**"]

# Email configuration
[auth.email]
enable_signup = true
enable_confirmations = true

[functions.document-processor]
enabled = true
verify_jwt = true
import_map = "./functions/document-processor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/document-processor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/document-processor/*.html" ]
