
# Auth configuration
[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "https://exora-guardian-healthcare.vercel.app/**",
  "https://exorahealth.com.au/**",
  "https://www.exorahealth.com.au/**",
  "https://staging.exorahealth.com.au/**",
  "https://www.staging.exorahealth.com.au/**"
]

# Email configuration
[auth.email]
enable_signup = true
enable_confirmations = true

# Guardian v7 Phase 1 Functions
[functions.document-processor]
enabled = true
verify_jwt = true
import_map = "./functions/document-processor/deno.json"
entrypoint = "./functions/document-processor/index.ts"

# Disabled for Phase 1 - These are complex functions handled by background workers
# [functions.document-normalizer]
# enabled = false

# [functions.quality-guardian] 
# enabled = false
