/**
 * Pass 1 Strategy-A Type Definitions
 *
 * Created: 2025-11-29
 * Purpose: TypeScript interfaces for Pass 1 Strategy-A entity detection
 * Reference: PASS1-STRATEGY-A-MASTER.md Section 4.5
 */

// =============================================================================
// ENTITY TYPES
// =============================================================================

/**
 * Entity types matching universal_medical_codes.entity_type
 * Used by Pass 1.5 for code shortlisting
 */
export type Pass1EntityType =
  | 'medication'
  | 'condition'
  | 'procedure'
  | 'observation'
  | 'allergy'
  | 'lab_result'
  | 'vital_sign'
  | 'physical_finding'
  | 'immunisation';

/**
 * Valid entity types for runtime validation
 */
export const VALID_ENTITY_TYPES: Pass1EntityType[] = [
  'medication',
  'condition',
  'procedure',
  'observation',
  'allergy',
  'lab_result',
  'vital_sign',
  'physical_finding',
  'immunisation'
];

// =============================================================================
// SAFE-SPLIT TYPES (from Pass 0.5)
// =============================================================================

/**
 * Safe-split point types generated by Pass 0.5
 * Used for batching large encounters
 */
export type SafeSplitType =
  | 'header'
  | 'footer'
  | 'whitespace'
  | 'page_break'
  | 'section_end'
  | 'forced';

/**
 * Safe-split point from healthcare_encounters.safe_split_points
 */
export interface SafeSplitPoint {
  page: number;
  split_y: number;
  split_type: SafeSplitType;
  marker?: string;
}

// =============================================================================
// AI RESPONSE TYPES (What AI Model Returns)
// =============================================================================

/**
 * Single entity detected by AI
 */
export interface Pass1Entity {
  id: string;                    // e.g., "e1", "e2"
  original_text: string;         // Raw text from document
  entity_type: Pass1EntityType;
  aliases: string[];             // Max 3 alternative names
  y_coordinate: number | null;   // Y position on page
  page_number: number;           // 1-indexed page number
}

/**
 * Bridge schema zone detected by AI
 * Defines Y-coordinate region for a schema type
 */
export interface Pass1BridgeSchemaZone {
  schema_type: string;   // 'medications', 'lab_results', 'vitals', etc.
  page_number: number;   // 1-indexed page number
  y_start: number;       // Top of zone
  y_end: number;         // Bottom of zone
  entity_count?: number; // Expected count of entities in this zone (for validation)
}

/**
 * Complete AI response structure
 */
export interface Pass1AIResponse {
  entities: Pass1Entity[];
  bridge_schema_zones: Pass1BridgeSchemaZone[];
}

// =============================================================================
// INPUT TYPES
// =============================================================================

/**
 * Input for processing a shell file
 * Entry point for Pass1Detector.processShellFile()
 */
export interface Pass1ShellFileInput {
  shell_file_id: string;
  patient_id: string;
  processing_session_id: string;
}

/**
 * Encounter data loaded from healthcare_encounters
 */
export interface EncounterData {
  id: string;                           // healthcare_encounter UUID
  shell_file_id: string;
  patient_id: string;
  start_page: number;                   // 1-indexed
  end_page: number;                     // 1-indexed
  page_count: number;                   // Computed: end_page - start_page + 1
  safe_split_points: SafeSplitPoint[];  // From Migration 70
  enhanced_ocr_text: string;            // Y-only format from shell_files
}

/**
 * Batch definition for processing
 */
export interface BatchDefinition {
  index: number;              // 0-based batch index
  pageRangeStart: number;     // 1-indexed start page
  pageRangeEnd: number;       // 1-indexed end page
  ocrTextSlice: string;       // Portion of OCR text for this batch
}

// =============================================================================
// OBSERVABILITY TYPES (Database Records)
// =============================================================================

/**
 * Batch state during processing
 */
export type BatchStatus = 'pending' | 'processing' | 'succeeded' | 'failed';

/**
 * Encounter result record (maps to pass1_encounter_results)
 */
export interface EncounterResultRecord {
  id?: string;
  shell_file_id: string;
  healthcare_encounter_id: string;
  processing_session_id: string;
  patient_id: string;
  page_count: number;
  batching_used: boolean;
  batches_total: number;
  status: BatchStatus;
  batches_succeeded: number;
  batches_failed: number;
  total_retries_used: number;
  started_at?: string;
  completed_at?: string;
  total_duration_ms?: number;
  total_input_tokens: number;
  total_output_tokens: number;
  total_entities_detected: number;
  total_zones_detected: number;
  failure_batch_index?: number;
  error_code?: string;
  error_summary?: string;
}

/**
 * Batch result record (maps to pass1_batch_results)
 */
export interface BatchResultRecord {
  id?: string;
  healthcare_encounter_id: string;
  pass1_encounter_result_id: string;
  processing_session_id: string;
  batch_index: number;
  page_range_start: number;
  page_range_end: number;
  status: BatchStatus;
  attempt_count: number;
  max_attempts: number;
  started_at?: string;
  completed_at?: string;
  duration_ms?: number;
  ai_model_used?: string;
  input_tokens?: number;
  output_tokens?: number;
  error_code?: string;
  error_message?: string;
  error_context?: Record<string, any>;
  had_transient_failure: boolean;
  transient_error_history?: AttemptRecord[];
  entities_detected?: number;
  zones_detected?: number;
}

/**
 * Entity detection record (maps to pass1_entity_detections)
 */
export interface EntityDetectionRecord {
  healthcare_encounter_id: string;
  shell_file_id: string;
  patient_id: string;
  processing_session_id: string;
  entity_sequence: number;
  original_text: string;
  entity_type: Pass1EntityType;
  aliases: string[];
  y_coordinate: number | null;
  page_number: number;
  bridge_schema_zone_id?: string;
}

/**
 * Bridge schema zone record (maps to pass1_bridge_schema_zones)
 */
export interface BridgeSchemaZoneRecord {
  id?: string;
  healthcare_encounter_id: string;
  processing_session_id: string;
  schema_type: string;
  page_number: number;
  y_start: number;
  y_end: number;
}

/**
 * Attempt record for transient error history
 */
export interface AttemptRecord {
  attempt: number;
  error_code: string;
  error_message: string;
  timestamp: string;
  retry_delay_ms?: number;
}

// =============================================================================
// BATCH STATE TRACKING
// =============================================================================

/**
 * Internal batch state during retry-until-complete processing
 */
export interface BatchState {
  index: number;
  batch: BatchDefinition;
  status: BatchStatus;
  attempt: number;
  result: BatchProcessingResult | null;
  errors: AttemptRecord[];
  batchResultId?: string;
}

/**
 * Result from processing a single batch
 */
export interface BatchProcessingResult {
  success: boolean;
  parsed: Pass1AIResponse;
  batchResultId: string;
  inputTokens: number;
  outputTokens: number;
  durationMs: number;
}

// =============================================================================
// PROCESSING RESULT TYPES
// =============================================================================

/**
 * Result from processing a single encounter
 */
export interface EncounterProcessingResult {
  success: boolean;
  encounterId: string;
  encounterResultId: string;
  entitiesDetected: number;
  zonesDetected: number;
  batchCount: number;
  totalRetries: number;
  durationMs: number;
  error?: string;
  errorCode?: string;
}

/**
 * Result from processing entire shell file
 */
export interface Pass1Result {
  success: boolean;
  shellFileId: string;
  sessionId: string;
  encountersProcessed: number;
  encountersSucceeded: number;
  encountersFailed: number;
  totalEntities: number;
  totalZones: number;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalDurationMs: number;
  failedEncounterId?: string;
  errorCode?: string;
  errorSummary?: string;
}

// =============================================================================
// CONFIGURATION TYPES
// =============================================================================

/**
 * Pass 1 detector configuration
 *
 * Note: Model selection is now handled via environment variables (PASS_1_USE_*)
 * and the shared AI provider system. The 'model' field is auto-populated.
 */
export interface Pass1Config {
  model: string;                    // Auto-set from env var selection (e.g., 'gpt-4o-mini')
  temperature: number;              // e.g., 0.1
  max_tokens: number;               // e.g., 4096
  max_retries: number;              // Default: 3
  concurrency_limit: number;        // Default: 5 (for p-limit)
  batch_min_pages: number;          // Default: 3
  batch_max_pages: number;          // Default: 10
  batch_hard_ceiling: number;       // Default: 50
  include_zones_in_prompt: boolean; // Default: true - set false to test entity-only extraction
}

/**
 * Default configuration values
 */
export const DEFAULT_PASS1_CONFIG: Partial<Pass1Config> = {
  model: 'gpt-4o-mini',
  temperature: 0.1,
  max_tokens: 4096,
  max_retries: 3,
  concurrency_limit: 5,
  batch_min_pages: 3,
  batch_max_pages: 10,
  batch_hard_ceiling: 50,
  include_zones_in_prompt: true  // Production: zones enabled
};

// =============================================================================
// METRICS UPDATE TYPES
// =============================================================================

/**
 * Updates for pass1_entity_metrics table
 */
export interface Pass1MetricsUpdate {
  ai_model_used: string;
  encounters_total: number;
  encounters_succeeded: number;
  encounters_failed: number;
  batches_total: number;
  batches_succeeded: number;
  total_retries_used: number;
  failure_encounter_id?: string;
  error_code?: string;
  error_summary?: string;
  entities_detected: number;
  processing_time_ms: number;
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
}

/**
 * Updates for ai_processing_sessions.pass1_status
 */
export type Pass1SessionStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'skipped';
