#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Only run if any package.json files changed
changed="$(git diff --cached --name-only | grep -E '(^|/)package\.json$' || true)"
[ -z "$changed" ] && exit 0

# Update lockfile and auto-stage it
pnpm install --lockfile-only --ignore-scripts
git add pnpm-lock.yaml
